---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  event:
  - cron
  - custom
  - tag

steps:
- name: build
  image: plugins/docker
  settings:
    registry: registry.fk.jochum.dev
    username: robot$jo-micro+drone
    password: 
      from_secret: registry.fk.jochum.dev-robot
    dockerfile: ./docker/router/Dockerfile
    context: ./docker/router/
    repo: registry.fk.jochum.dev/jo-micro/router
    build_args:
    - VERSION=${DRONE_TAG:1}
    auto_tag: true
