version: '3'

vars:
  GIT_TAG: 
    sh: git tag --points-at HEAD
  GIT_COMMIT:
    sh: git rev-parse --short HEAD
  GIT_DIRTY:
    sh: git status -s
  VERSION:
    sh: if test "{{.GIT_DIRTY}}" != ""; then echo "{{.GIT_COMMIT}}-dirty"; elif test "{{.GIT_TAG}}" != ""; then echo "{{.GIT_TAG}}"; else echo "{{.GIT_COMMIT}}"; fi

tasks:
  default:
    cmds: 
      - task: volume
      - task: podman

  version:
    cmds:
      - echo "{{.VERSION}}"

  volume:
    run: "once"
    cmds:
      - podman volume inspect micro_router_go 1>/dev/null 2>&1 || podman volume create micro_router_go

  protoc:
    desc: Generate protobruf go files
    sources:
      - ./proto/**/*.proto
    cmds:
      - task: builder
        vars:
          CLI_ARGS: /scripts/protoc_gen.sh

  build:podman:
    deps:
      - protoc
    cmds:
      - podman build -v "{{.VOLUME_PATH}}:/go:rw" --build-arg VERSION={{.VERSION}} -t registry.fk.jochum.dev/jo-micro/router:latest -f ./docker/router/Dockerfile .
    vars:
      VOLUME_PATH:
        sh: podman volume inspect micro_router_go  --format "{{"{{"}}.Mountpoint{{"}}"}}"
  
  podman:
    desc: Generate docker container for go-micro-router tagged as registry.fk.jochum.dev/jo-micro/router:latest and :GIT_TAG if theres a tag
    cmds:
      - task: build:podman

  tidy:
    desc: Run "go mod tidy" in a container
    cmds:
      - task: builder
        vars:
          CLI_ARGS: go mod tidy

  update:
    desc: Run "go get -u ./..." in a container
    cmds:
      - task: builder
        vars:
          CLI_ARGS: /scripts/upgrade_deps.sh

  rm:
    desc: Remove all persistent data
    cmds:
      - podman image rm registry.fk.jochum.dev/jo-micro/router:latest || exit 0
      - podman volume rm micro_router_go || exit 0
      - rm -rf $PWD/.task